# ######################### #
# 此配置文件是【开发环境】的配置 #
#  此配置文件需要被激活才会生效 #
# ######################## #

#开发服务端口号
server:
  port: 8888

# 连接数据库的配置参数
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #配置静态资源文件夹,classpath:static指原来的static文件夹
  web:
    resources:
      static-locations: file:D:/files,classpath:static

  #设置上传文件大小  默认1MB
  servlet:
    multipart:
      max-file-size: 10MB

# 当前项目中的自定义配置
blogsystem:
  # JWT相关配置
  jwt:
    # 生成和解析JWT时使用的secretKey
    secret-key: a9F8ujGDhjgFvfEd3SA90ukDS
    # JWT的有效时长,以分钟为单位
    duration-in-minute: 1440

# 日志的显示级别默认info(根包尽量这样写,若简写会扩大不必要的范围,多写比较麻烦)
logging:
  level:
    cn.tedu.blogsystem: trace

# 定义图片Path变量
image:
  dirPath: C:\Users\Administrator\IdeaProjects\blog-client\public\